# Generated by Django 2.0.4 on 2018-05-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_exhibitneighor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitneighor',
            name='direction',
            field=models.CharField(blank=True, choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West'), ('sw', 'SouthWest'), ('se', 'SouthEast'), ('ne', 'NorthEast'), ('nw', 'NorthWest')], help_text='Enter Direction', max_length=2, null=True),
        ),
    ]
