# Generated by Django 2.0.4 on 2018-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_auto_20180501_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='logoFileName',
            field=models.CharField(help_text='Enter a logo image', max_length=200, null=True),
        ),
    ]
