# Generated by Django 2.0.4 on 2018-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_auto_20180502_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dietDescription',
            field=models.TextField(help_text='Enter Diet Description', max_length=1000, null=True),
        ),
    ]
