# Generated by Django 2.0.4 on 2018-05-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_animal_dietdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='videoLink',
            field=models.CharField(help_text='Enter Video Link', max_length=200, null=True),
        ),
    ]
